### ISSUE TITLE
On Kali 2.0 I get syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by marianobilli** [Nyzo/airssl#1]
If I run the script on Kali 2.0 i get 

./Air-ssl.sh: line 4: syntax error near unexpected token `newline'
./Air-ssl.sh: line 4:`<!DOCTYPE html>'

Bellow prerequisites were met
$ apt-get update
$ apt-get upgrade
$ apt-get install driftnet ettercap-graphical isc-dhcp-server sslstrip aircra

Cheers!

**Comment by enzomerand** [comment]
there is nothing at line 4...
Use this script, is an update of airssl https://github.com/Nyzo/myHotspot
